apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tinymon.fullname" . }}
  labels:
    {{- include "tinymon.labels" . | nindent 4 }}
data:
  APP_DEBUG: "false"
  SMTP_FROM_NAME: {{ .Values.smtp.fromName | quote }}
  SMTP_ENCRYPTION: {{ .Values.smtp.encryption | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  VAPID_SUBJECT: {{ .Values.vapid.subject | quote }}
