apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tinymon.fullname" . }}
  labels:
    {{- include "tinymon.labels" . | nindent 4 }}
type: Opaque
data:
  ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
  SMTP_HOST: {{ .Values.smtp.host | b64enc | quote }}
  SMTP_USER: {{ .Values.smtp.user | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}
  SMTP_FROM_EMAIL: {{ .Values.smtp.fromEmail | b64enc | quote }}
  ALERT_RECIPIENTS: {{ .Values.alertRecipients | b64enc | quote }}
  PUSH_API_KEY: {{ .Values.pushApiKey | b64enc | quote }}
  VAPID_PUBLIC_KEY: {{ .Values.vapid.publicKey | b64enc | quote }}
  VAPID_PRIVATE_KEY: {{ .Values.vapid.privateKey | b64enc | quote }}
